---
- name: Install docker
  hosts: elk
  become: true
  tasks:
    - name: set vm.max_map_count to 262144 in sysctl
      sysctl: name={{ item.key }} value={{ item.value }}name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: install python3
      apt:
        name: python3-pip
        state: present

    - name: install docker python package
      pip:
        name: docker
        state: present

    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Make docker service started
      systemd:
        enabled: yes
        name: docker
